name: Deploy to HAS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Home Automation Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to HAS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HAS_SSH_HOST }}
        username: ${{ secrets.HAS_SSH_USER }}
        key: ${{ secrets.HAS_SSH_PRIVATE_KEY }}
        port: 2222 # Používám port 2222, který je pravděpodobně namapován v docker-compose
        script: |
          echo "🚀 Starting deployment to HAS..."
          cd /home/orchestration
          echo " pulling latest changes from GitHub..."
          git pull origin master
          echo " rebuilding and restarting services..."
          docker-compose up -d --build
          echo " pruning old docker images..."
          docker image prune -f
          echo "✅ Deployment finished successfully!"